sudo: required
services:
  - docker
before_install:
  # Creat amb tavis-cli tools per Ruby
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  # Instal.lació de l'SDK de GCloud
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Actualitzem kubectl
  - gcloud components update kubectl
  # Definim autenticació des de Travis
  - gcloud auth activate-service-account --key-file sevice-account.json


